### ISSUE TITLE
The state of date-chinese calendar JavaScript package in Q2 2022?

### ISSUE THREAD

**Issue by lancejpollard** [commenthol/date-chinese#8]
I am new to the [Chinese Calendar](https://en.wikipedia.org/wiki/List_of_calendars), and wondering what is/are the best libraries are for working with them in JavaScript. Where does your project fit on the spectrum? Is it considered complete? If not, what is missing? If so, how does it relate to the other Chinese calendars on that Wiki?

> - Chinese Calendar, Dàmíng origin	
>   - lunisolar
>   - 510
>   - China	
>   - Created by Zu Chongzhi
>   - most accurate calendar in the world at its invention
> - Chinese Calendar, Wùyín origin
>   - lunisolar
>   - 619
>   - China
>   - First Chinese calendar to use the true moon motion
> - Four Seasons and Eight Nodes
>   - solar
>   - Bronze Age(?)	
>   - China
>   - The years is divided into four seasons, and each season is divided into a festival and three months. The start and middle of each season is the key node of the year.
> - Genesis Calendar
>   - lunisolar
>   - Han dynasty
>   - China
>   - Introduced the "month without mid-climate is intercalary" rule; based on a solar year of 365385⁄1539 days and a lunar month of 2943⁄81 days (19 years=235 months=693961⁄81 days).
> - Seasonal Constitution
>   - solar
>   - 1645
>   - China
>   - First Chinese Calendar to use the true motion of the sun.
> - Seasonal Instruction
>   - solar
>   - 1281
>   - China
>   - Based on a solar year of 365.2425 (equal to the Gregorian year)
> - Six Ancient Calendars
>   - lunisolar
>   - Iron Age
>   - China
>   - Six classical (Zhou era) calendars: Huangdi, Zhuanxu, Xia, Yin, Zhou's calendar and Lu.
> - Six Imperial Calendars (ß)
>   - solar
>   - Ming dynasty
>   - China
>   - In use 1368-1644
> - Japanese calendar
>   - lunisolar

Thank you so much for your time and for this great looking project!

**Comment by commenthol** [comment]
This project is based on the lunisolar [Shixian calendar](https://en.m.wikipedia.org/wiki/Chongzhen_calendar) which is in use since the 17th century.
Support for historical calendars as described in your list are out of scope for this project.
