### ISSUE TITLE
Unsure about `leap` parameter

### ISSUE THREAD

**Issue by 6xtvo** [commenthol/date-chinese#9]
I'm not sure what value to put for the `leap` parameter for `CalendarChinese` or what it's for, could you explain it in more detail?

**Comment by commenthol** [comment]
Hi @r1zyn,
The leap month is determined by the chinese calendar. 
So if you have a chinese date which falls into a leap month you'd need to set leap=true.
I recommend reading http://chineseastrologyforkids.weebly.com/leap-years.html
